global:
  scrape_interval: 5s
  evaluation_interval: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['10.0.0.53:9093']

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: 'open5gs-amf'
    static_configs:
      - targets: ['10.0.0.20:9090']

  - job_name: 'open5gs-upf'
    static_configs:
      - targets: ['10.0.0.22:9090']

  - job_name: 'mining-telemetry'
    static_configs:
      - targets: ['10.0.0.40:8000']

  - job_name: 'mec-edge'
    static_configs:
      - targets: ['10.0.0.45:5000']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['10.0.0.51:9100']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
